apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ssl-checker.fullname" . }}-config
data: 
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.ASPNETCORE_ENVIRONMENT }}"
  DOTNET_ENVIRONMENT: "{{ .Values.config.DOTNET_ENVIRONMENT }}"
  CERT_CHECK_FROM_DAYS_MORE: "{{ .Values.config.CERT_CHECK_FROM_DAYS_MORE }}"
  EXEC_HOUR: "{{ .Values.config.EXEC_HOUR }}"
  DOMAINS: "{{ .Values.config.DOMAINS }}"